mysql.config:
  conn:
    host: 'localhost'
    port: 3306
    db: 'dbetl'
    user: 'root'
    password: 'xxxxxx'
    charset: 'utf8'

redis.config:
  host: 'localhost'
  port: '6379'
  channels:
    matching: 'chan:matching'
    broadcase: 'chan:updates'